homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('message/', views.message, name='message'),
]

story/story/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

class ClassYear(models.Model):
    year = models.CharField(max_length=30)

homepage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'Homepage.html')

def message(request):
    return render(request, 'Message.html')

def home(request):
    return render(request, 'Homepage.html')

homepage/templates/Homepage.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <title>Website Ferdi Salim Sungkar</title>
  </head>
  <body>
    <div class="bg">
        <div class="one">
            <ul class="nav justify-content-center">
                <li class="about">
                  <a class="nav-link" href="#one">about</a>
                </li>
                <li class="skills">
                  <a class="nav-link" href="#two">skills</a>
                </li>
                <li class="contact">
                    <a class="nav-link" href="#three">contact</a>
                </li>
                <li class="goodbye">
                    <a class="nav-link" href="{% url 'homepage:message' %}">bye</a>
                </li>
            </ul>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md">
                    <h1 id="top">WELCOME</h1> 
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

        <div class="two">
            <div class="row">
                <div class="col-lg-4">
                    <img class="white-photo" src="{% static 'Images/white.jpeg' %}" alt="white">
                    <img class="my-profile-photo" src="{% static 'Images/profilephoto.jpeg' %}" alt="profile-photo">
                </div>
                <div class="col-lg">
                    <h2 id="one">
                        FERDI SALIM SUNGKAR           
                    </h2>
                    <h5>
                        My name is Ferdi, people usually call me Ferdi, my parents also call me Ferdi, basically everyone call me Ferdi.
                        I'm currently a student of Computer Science in University of Indonesia, and i'm making this website as an assignment for my
                        Web Development and Programming course.
                    </h5>
                    <h5></h5>
                    <h5>
                        I'm starting to be more and more interseted about web developing and designing,
                        even though my design is not that good.
                    </h5>
                    <h5></h5>
                </div>
            </div>
        </div>
    </div>

    <div class="bg2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md">
                    <h1 id="two">SKILLS</h1> 
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

        <div class="three">
            <div class="container">
                <h5></h5>
                <div class="row">
                    <div class="col-md-12">
                        <h5>HTML</h5>
                        <h6></h6>
                        <div class="progress">
                            <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 70%; color: #E3E8EA;"></div>
                        </div>
                    </div>
                </div>
                <h5></h5>
                <h5></h5>
                <div class="row">
                    <div class="col-md-12">
                        <h5>CSS</h5>
                        <h6></h6>
                        <div class="progress">
                            <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                        </div>
                    </div>
                </div>
                <h5></h5>
                <h5></h5>
                <div class="row">
                    <div class="col-md-12">
                        <h5>Java</h5>
                        <h6></h6>
                        <div class="progress">
                            <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                        </div>
                    </div>
                </div>
                <h5></h5>
                <h5></h5>
                <div class="row">
                    <div class="col-md-12">
                        <h5>Python</h5>
                        <h6></h6>
                        <div class="progress">
                            <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br><br>
        </div>

        <div class="bg3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md">
                        <h1 id="three">CONTACT</h1> 
                    </div>
                    <div class="col-md-1"></div>
                </div>
                <br><br><br><br><br><br><br><br><br>
            </div>
            <div class="four">
                <h5>
                    FERDI SALIM SUNGKAR           
                </h5>
                <h7>
                    ferdisgk@gmail.com
                </h7>
                <br>
                <h7>
                    +62 878 8070 7645
                </h7>
                <br><br>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1">
                            <a href="https://www.instagram.com/ferdisungkar/">
                                <img alt="Instagram" src="{% static 'Images/Logo/Instagram.png' %}" height="50">
                        </div>
                        <div class="col-sm-1">
                            <a href="https://twitter.com/ferdisungkar">
                                <img class="twitter" src="{% static 'Images/Logo/twitter.png' %}" height="50">
                        </div>
                        <div class="col-sm-1">
                            <a href="https://www.linkedin.com/in/ferdi-sungkar-99760417b/">
                                <img class="linkedin" src="{% static 'Images/Logo/linkedin.png' %}" height="50">
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>

    </div>

    
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/Message.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <title>message me!</title>
  </head>
  <body>
    <div class="bg3">
        <div class="one">
            <ul class="nav justify-content-center">
                <li class="home">
                  <a class="nav-link" href="{% url 'homepage:index' %}">home</a>
                </li>
            </ul>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <h1 id="goodbye">GOOD BYE</h1> 
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>

        <br><br><br><br><br><br><br><br><br><br><br><br>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>